swagger:
  enable: true
server:
  port: 9090

#spring配置
spring:
  http:
    multipart:
      maxFileSize: 10Mb
  #数据源配置
  datasource:
    url: jdbc:mysql://122.51.251.251:3306/test_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: admin
    password: 1212huang1205
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
